# Generated by Django 5.2.1 on 2025-05-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_creado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_creado'],
            },
        ),
    ]
